### ISSUE TITLE
Question about scikit_roughsets which can not be installed using pip 

### ISSUE THREAD

**Issue by WilliamWangPeng** [paudan/scikit-roughsets#2]
Hi dear author,  
    It's an honor to write this issue here, I'm trying to run this program, but some error happened below:

```
wangpeng@dacent:~/tools/renderbench/machine-learning/scikit-roughsets/tests$ python tests.py 
Traceback (most recent call last):
  File "tests.py", line 3, in <module>
    from scikit_roughsets.roughsets import RoughSetsReducer
ImportError: No module named scikit_roughsets.roughsets

```

    I can not use pip to install scikit_roughsets which shows "ERROR: No matching distribution found for scikit_roughsets "  do you know how to run this program?

![image](https://user-images.githubusercontent.com/51076736/155257726-ad5a2d9d-9eea-446f-9a26-8f712b175897.png)  

thank you 
best regards
William

**Comment by Kingsley-opoku** [comment]
Dear Author, I am trying to run the module of the scikit_roughsets but, I am getting this error 
 ModuleNotFoundError: No module named 'sklearn.feature_selection.base'. I think it is because the module SelectorMixin is no longer at 'sklearn.feature_selection.base' but just 'sklearn.feature_selection'. 
Please, how can I fix the problem? Thank you for your implementation

**Comment by paudan** [comment]
Hi @Kingsley-opoku, glad you found this code useful! I have updated the code to work with the most recent version of scikit-learn; should work with all recent Python versions.

I have also updated README for more clear installation instructions
